/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kuDialogTest_kuCppWrapperTest */

#ifndef _Included_kuDialogTest_kuCppWrapperTest
#define _Included_kuDialogTest_kuCppWrapperTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kuDialogTest_kuCppWrapperTest
 * Method:    kuWrapperHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kuDialogTest_kuCppWrapperTest_kuWrapperHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     kuDialogTest_kuCppWrapperTest
 * Method:    kuWrapperAddTest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_kuDialogTest_kuCppWrapperTest_kuWrapperAddTest
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
